<table>
	<tr>
		<td>Ingrese Usuario</td>
		<td>:</td>
		<td><input type='text' id='usuario_cancelacion' name='usuario_cancelacion'></input> </td>
	</tr>
	<tr>
		<td colspan='2'>Ingrese Solicitud</td>
		<td>:</td>
	</tr>
	<tr>
		
		<td colspan='2'>&nbsp;</td>
		<td align='center'><textarea name="descripcion" id="descripcion" style='width:300px;'></textarea></td>
	</tr>
	<tr>
		
		<td colspan='2'>
			<input type='submit' id='enviar' name='enviar' value='Enviar Solicitud'></input>
		</td>
		<td>
			<input type='submit' id='cancelar' name='cancelar' value='Cancelar Solicitud'></input>
		</td>
	</tr>
	
</table>