<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Cancelar suspension | Kotear.pe</title>
<link href="<?=URL_STATIC?>css/global.css" rel="stylesheet" type="text/css" media="screen" />
<!--[if lt IE 8]>
<link href="f/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->
</head>
<body>
    <form id="frmSuspended" name="frmSuspended" class="" method="post" action="<?php echo $this->url(array('controller'=>'suspencion','action'=>'cancelacion')) ?>">
        <?php if (isset($this->errors)){ ?>
        <div>
          <? foreach ($this->errors as $index =>$error){?>
          <? if ($error!=null){ ?>
          <br/><b><?=$index?></b><br/>
          <?=implode('<br/>',$error);?>
          <?}?>
          <?}?>
        </div>
        <?}?>
        <?php if (isset($this->msg)){?>
                <div class="mensajeerror">
                    <img src='<?php $this->baseUrl()?>/img/icons/warning.gif'/><?php echo $this->msg; ?>
                </div>
            <?php }?>
    	<h2>Cancelar suspensión</h2>

        <p> <strong>username</strong> tu cuenta se encuentra suspendida, puedes enviar un mensaje solicitando la cancelación de tu suspensión utilizando la casilla de texto siguiente.</p>

        <p class="msg">
          <label>Nueva clave:  </label>
          <textarea name="msg" id="msg" class="required" cols="30" rows="5" ></textarea>
        </p>

        <p class="buttons">
			<input value="Continuar" type="submit" id="continuar" name="continuar" >
			<input value="Cancelar" type="button" id="cancel" class="close" name="cancel"
                   onclick="window.location.href='<?php echo $this->url(array('controller'=>'acceso','action'=>'logout')) ?>'">
		</p>
    </form>
</body>
</html>