INSERT INTO KO_TIPO_PRODUCTO(ID,DES) VALUES (1, 'NUEVO');
INSERT INTO KO_TIPO_PRODUCTO(ID,DES) VALUES (1, 'USADO');
INSERT INTO KO_TIPO_USUARIO(ID,DES) VALUES(1,'VENDEDOR');
INSERT INTO KO_TIPO_USUARIO(ID,DES) VALUES(1,'COMPRADOR');
INSERT INTO KO_TIPO_SUSPENCION(ID,DES) VALUES(1,'GRAVE');
INSERT INTO KO_TIPO_SUSPENCION(ID,DES) VALUES(2,'LEVE');
INSERT INTO KO_TIPO_SUSPENCION(ID,DES) VALUES(3,'MODERADA');
INSERT INTO KO_TIPO_NOTIFICACION(ID,DES) VALUES(1,'Activación de Cuenta');
INSERT INTO KO_TIPO_NOTIFICACION(ID,DES) VALUES(2,'Apercibimiento');
INSERT INTO KO_TIPO_MOTIVO(ID,DES) VALUES(1,'Cancelación de Compra');
INSERT INTO KO_TIPO_MOTIVO(ID,DES) VALUES(2,'Apercibiminto');
INSERT INTO KO_TIPO_MENSAJE(ID,DES) VALUES(1,'Preguntas');
INSERT INTO KO_TIPO_MENSAJE(ID,DES) VALUES(2,'Respuestas');
INSERT INTO KO_TIPO_MENSAJE(ID,DES) VALUES(3,'Comentarios');
INSERT INTO KO_TIPO_MENSAJE(ID,DES) VALUES(4,'Reclamos');


//Ubigeos
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('1', 'Amazonas');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('2', 'Ancash');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('3', 'Apurímac');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('4', 'Arequipa');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('5', 'Ayacucho');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('6', 'Cajamarca');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('7', 'Callao');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('8', 'Cusco');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('9', 'Huancavelica');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('10', 'Huánuco');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('11', 'Ica');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('12', 'Junín');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('13', 'La Libertad');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('14', 'Lambayeque');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('15', 'Lima');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('16', 'Loreto');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('17', 'Madre de Dios');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('18', 'Moquegua');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('19', 'Pasco');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('20', 'Piura');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('21', 'Puno');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('22', 'San Martín');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('23', 'Tacna');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('24', 'Tumbes');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('25', 'Ucayali');
INSERT INTO KO_UBIGEO(ID_UBIGEO,NOM) VALUES('0', 'Otros');

