<h3 class="k-title"><span></span>Kotear | Ingresar codigo:</h3>
<div id="code-error"></div>
      <p>Ingrese el código de verificación que se le ha enviado a su correo electronico.</p>
<form id="code-recover-form" method="post" action=""> 
    <div class="form-horizontal">
        <div class="control-group">
            <label for="code-verify" class="control-label">Código de verificación</label>
            <div class="controls">
                <input type="text" size="30" name="vcod" id="code-verify" tabindex="1">
            </div>
        </div>
        <div class="control-group align-center">
             <button type="submit" class="btn-kotear" tabindex="2">Continuar</button>
             <a href="javascript:;" class="btn-close" tabindex="3">Cancelar</a>
        </div>
    </div> 
</form>