        <form id="login" name="login" method="post" action="">
          <p>
          Correo electronico:<br/>
          <input class="required" type="text" name="email" id="email" />
          <br>
          </p>
          <p>
          Cuerpo del mensaje:<br/>
          <input class="required" type="text" name="body" id="body" />
          <button type="submit">Continuar</button>
        </form>