<div id="navbar-example" class="navbar navbar-static">
    <div class="navbar-inner">
        <div class="container" style="width: auto;">
            <a class="brand" href="#"><img src="<?= URL_STATIC . 'img/admin/logo-mini.jpg'?>" /></a>
            <ul class="nav pull-right">
                <li id="fat-menu" class="dropdown">
                    <a href="#" id="drop3" role="button" class="dropdown-toggle" 
                       data-toggle="dropdown">
                        <?=$this->layout()->auth['admin']->NOM?> 
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <!--<li><a tabindex="-1" href="#">Actualizar Perfil</a></li>
                        <li class="divider"></li>-->
                        <li>
                            <a tabindex="-1" href="/admin/auth/logout">
                                Cerrar Sesion
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
