<?php 

if (count($this->data)>0) {
    if ($this->tipoModulo == 1) { ?>
        <table class="fbTable table table-bordered table-striped">
            <thead >
                <tr>
                    <th ></th>
                    <th >Código</th>
                    <th >Nombre</th>
                    <th >Ord.</th>
                    <th >Módulo</th>
                    <th >Link</th>
                    <th >Hab</th>
                </tr>
            </thead>
            <tbody>
            <?php
                $class = array(0 => 'even', 1 => '');
                $i = 0;
                foreach ($this->data as $data) : 
            ?>
                    <tr class="<?= $class[$i++ % 2] ?>">
                        <td class="headAccion">
                            <a href="javascript:;" class="apfbBtnOpenModal"
                               data-id="<?=$this->escape($data->K_ID_ITEM)?>">
                                <img src="<?= URL_STATIC . 'img/admin/pencil.png'?>" width="12" height="12"/>
                            </a>
                        </td>
                        <td ><?= $this->escape($data->K_ID_ITEM) ?></td>
                        <td ><?= $this->escape($data->K_DESC) ?></td>
                        <td ><?= $this->escape($data->K_ORDEN) ?></td>
                        <td ><?= $this->escape($data->K_NOM_MODULO) ?></td>
                        <td ><?= $this->escape($data->K_LINK) ?></td>
                        <td ><?= $this->escape($data->K_ID_ESTADO) ?></td>
                    </tr>
            <?  endforeach; ?>
            </tbody>
        </table>
    <?php } elseif ($this->tipoModulo == 2) { ?>
        <table class="fbTable table table-bordered table-striped">
            <thead >
                <tr>
                    <th ></th>
                    <th >Modulo</th>
                    <th >Cod. Aviso</th>
                    <th >Titulo Aviso</th>
                    <th >Apodo</th>
                    <th >Activo</th>
                </tr>
            </thead>
            <tbody>
            <?php
                $class = array(0 => 'even', 1 => '');
                $i = 0;
                foreach ($this->data as $data) : 
            ?>
                    <tr class="<?= $class[$i++ % 2] ?>">
                        <td class="headAccion">
                            <a href="javascript:;" class="apfbBtnOpenModal"
                               data-id="<?=$this->escape($data->K_ID_MODULO_AVISO)?>">
                                <img src="<?= URL_STATIC . 'img/admin/pencil.png'?>" width="12" height="12"/>
                            </a>
                        </td>
                        <td ><?= $this->escape($data->K_NOM_MODULO) ?></td>
                        <td ><?= $this->escape($data->K_ID_AVISO) ?></td>
                        <td ><?= $this->escape($data->K_TITULO) ?></td>
                        <td ><?= $this->escape($data->K_APODO) ?></td>
                        <td ><?= $this->escape($data->K_COLOCADO) ?></td>
                    </tr>
            <?  endforeach; ?>
            </tbody>
        </table>
    <?php } ?>
    <div class="fbPagination">
        <?= $this->paginationControl($this->paginador, 'Sliding', '_partials/_pag.phtml') ?>
    </div>
<?php } else { ?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>Oh!</strong> No hay datos registrados con esos parámetros.
    </div>
<?php } ?>