<h4 class="header-seccion">Buscar Aviso</h4>
<form method="post" action="/item/especial-buscar" form-edit="/item/form" enctype="application/x-www-form-urlencoded" id="formSearchEspecial">
    <div class="ahero-unit">
        <div class="form-inline aFormLine">
            <label class="awidth2 optional" for="a_codigoAviso">Código aviso:</label>
            <span class="element"><?= $this->form->a_codigoAviso->renderViewHelper(); ?></span>
            <label class="awidth2 optional" for="a_apodo">Apodo:</label>
            <span class="element"><?= $this->form->a_apodo->renderViewHelper(); ?></span>
        </div>
        <div class="form-inline aFormLine">
                <label class="awidth2 optional" for="a_tipoDestaque">Tipo de destaque:</label>
                <span class="element"><?= $this->form->a_tipoDestaque->renderViewHelper(); ?></span>
        </div>
        <div class="form-inline aFormLine">
                <label class="awidth2 optional" for="a_fecIni">Desde:</label>
                <span class="element"><?= $this->form->a_fecIni->renderViewHelper(); ?></span>
                <label class="awidth2 optional" for="a_fecFin">Hasta:</label>
                <span class="element"><?= $this->form->a_fecFin->renderViewHelper(); ?></span>
        </div>
        <div class="form-actions">
                <input type="submit" class="btn btn-primary" value="Buscar" id="apfbBtnSearch" name="a_buscar">
        </div>
    </div>
</form>
<div id="afbResultAjax"></div>