<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>kotear</title>
    <!-- Bootstrap -->
    <link href="<?=URL_STATIC?>css/bootstrap/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="<?=URL_STATIC?>css/admin.css" rel="stylesheet" media="screen">
  </head>
  <body>
    <div id="wrapper" class="wrapper-admin">
      <!-- nav -->
      <div id="navbar-example" class="navbar navbar-static">
              <div class="navbar-inner">
                <div class="container" style="width: auto;">
                  <a class="brand" href="#">Kotear</a>
                  <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">Usuario <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li><a tabindex="-1" href="#">Actualizar Perfil</a></li>
                        <li class="divider"></li>
                        <li><a tabindex="-1" href="#">Cerrar Sesion</a></li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
      <!-- // nav -->
      <div id="colum-left">
            <!-- options -->
            <div class="accordion" id="accordion2">
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                    <i class="icon-wrench"></i> MANTENIMIENTOS
                  </a>
                </div>
                <div id="collapseOne" class="accordion-body collapse in">
                  <div class="accordion-inner">
                    <ul> 
                      <li><a href="#"> Administración Usuarios Portal</a></li>
                      <li><a href="#">Administración de Item</a></li>
                      <li><a href="#">Administración de Modulos</a></li>
                      <li><a href="#">Motivos Apercibimiento</a></li>
                      <li><a href="#">Simbología</a></li>
                      <li><a href="#">Tipo Destaque</a></li>
                      <li><a href="#">Texto Moderable</a></li>
                      <li><a href="#">Mantenimiento Dolar</a></li>
                      <li><a href="#">Diccionario de Palabras</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                    <i class="icon-asterisk"></i> PROCESOS
                  </a>
                </div>
                <div id="collapseTwo" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <ul> 
                      <li><a href="#">Item1</a></li>
                      <li><a href="#">Item2</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                  <i class="icon-eye-open"></i> SEGURIDAD
                  </a>
                </div>
                <div id="collapseThree" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <ul> 
                      <li><a href="#">Item1</a></li>
                      <li><a href="#">Item2</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                  <i class="icon-check"></i> ACCIONES
                  </a>
                </div>
                <div id="collapseFour" class="accordion-body collapse">
                  <div class="accordion-inner">
                     <ul> 
                      <li><a href="#">Item1</a></li>
                      <li><a href="#">Item2</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <!-- //options -->
      </div>
      <div id="colum-right">
        <ul class="breadcrumb">
          <li><a href="#">Home</a> <span class="divider">/</span></li>
          <li><a href="#">Library</a> <span class="divider">/</span></li>
          <li class="active">Data</li>
        </ul>
        <div class="form-inline">
            <div class="control-group">
                <label class="control-label" for="inputEmail">Email</label>
                <div class="control"> 
                  <input type="text" id="inputEmail" placeholder="Email">
                </div>
                <label class="control-label" for="inputPassword">Password</label>
                <div> 
                  <input type="password" id="inputPassword" placeholder="Password">
                </div>
            </div>
        </div>
          <table class="table table-bordered">
              <thead>
                <tr>
                  <th>#</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Username</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td rowspan="2">1</td>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
                </tr>
                <tr>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@TwBootstrap</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td colspan="2">Larry the Bird</td>
                  <td>@twitter</td>
                </tr>
              </tbody>
            </table>
      </div>
      <div class="clear"></div>
    </div>
  </body>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/f/js/libs/bootstrap/bootstrap.min.js"></script>
</html>