 <div id="account_navigation" class="clearfix">
 
        <ul id="koteando_menu_secc">
          <li id="km_opt1"><a href="<?php echo  $this->baseUrl()?>/usuario/compra/historial-compras/opc/categoria/codigo/0">Mis Compras</a></li>
          <li id="km_opt2"><a href="<?php echo  $this->baseUrl() ?>/usuario/venta/activas/opc/categoria/codigo/0">Mis Ventas</a></li>
          <li id="km_opt3" class="active"><a href="<?php echo $this->baseUrl() ?>/usuario/calificaciones/pendientes">Mis Calificaciones</a></li>
          <li id="km_opt4"><a href="<?php echo  $this->baseUrl() ?>/pagos/index/pendiente-de-pago">Kotear Pagos</a></li>
          <li id="km_opt5"><a href="<?php echo  $this->baseUrl()?>/usuario/edicion">Mis Datos</a></li>
        </ul>
		<ul class="koteando_tabs_menu">
          <li <?php if($op==1){?>class="active"<?php }?>><a href="<?php echo  $this->baseUrl()?>/usuario/calificaciones/pendientes">Calificaciones Pendientes</a></li>
          <!--<li <?php if($op==2){?>class="active"<?php }?>><a href="<?php echo  $this->baseUrl()?>/usuario/calificaciones/realizadas">Calificaciones Realizadas</a></li> -->
          <li <?php if($op==2){?>class="active"<?php }?>><a href="<?php echo  $this->baseUrl()?>/usuario/reputacion/ver">Mi Reputacion</a></li>
		  <li <?php if($op==3){?>class="active"<?php }?>><a href="<?php echo  $this->baseUrl()?>/usuario/calificaciones/realizadas">Calificaciones Realizadas</a></li>
        </ul>
		<ul class="koteando_rightmenu">
          <li><a href="#">Ayuda</a></li>
          <li><a href="#">Preguntas Frecuentes</a></li>
        </ul>
</div>
