<?php 
if (count($this->data)>0) { ?>
<div >
    <table class="fbTable table table-bordered table-striped">
        <thead >
            <tr>
                <th ></th>
                <th >Tag</th>
                <th >Url</th>
                <th >Prioridad</th>
                <th >Orden</th>
                <th >Estado</th>
            </tr>
        </thead>
        <tbody>
        <?php
            $class = array(0 => 'even', 1 => '');
            $i = 0;
            foreach ($this->data as $data) {
        ?>
                <tr class="<?= $class[$i++ % 2] ?>">
                    <td class="headAccion">
                        <a href="javascript:;" class="apfbBtnOpenModal"
                           data-id="<?=$this->escape($data->K_ID_PALABRA)?>">
                            <img src="<?= URL_STATIC . 'img/admin/pencil.png'?>" width="12" height="12"/>
                        </a>
                    </td>
                    <td ><?= $this->escape($data->K_TAG) ?></td>
                    <td ><?= $this->escape($data->K_URL) ?></td>
                    <td ><?= $this->escape($data->K_PRIORIDAD) ?></td>
                    <td ><?= $this->escape($data->K_ORDEN) ?></td>
                    <td ><?= $this->escape($data->K_ESTADO) ?></td>
                </tr>
        <?  } ?>
        </tbody>
    </table>
</div>
<div class="fbPagination">
    <?= $this->paginationControl($this->paginador, 'Sliding', '_partials/_pag.phtml') ?>
</div>
<?php } else { ?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>No hay datos registrados con esos parámetros.</strong>
    </div>
<?php } ?>