  <?php echo $this->action('buscador', 'busqueda', 'default'); ?>
  <blockquote>&nbsp;</blockquote>
  <div id="body-content" class="col-master">
    <div>
      <h3>Esta p&aacute;gina se encuentra en construcción, no est&aacute; disponible o fue removida.</h3>
    <blockquote>&nbsp;</blockquote>
    </div>
    <div id="error404">
      <br/>
      <p>Puedes ir a la <a href="<?php echo $this->baseUrl(); ?>" alt="página principal">p&aacute;gina principal</a> o encontrar las mejores ofertas <a href="<?php echo $this->baseUrl() . '/busqueda/categoria'; ?>">navegando por las distintas categor&iacute;as</a>.</p>
      <br />
      <p>Si quieres vender un art&iacute;culo, haz <a href="<?php echo $this->baseUrl() . '/usuario/publicacion/registro-destaque'; ?>">clic aqu&iacute;</a>.</p>      
      <p>Si el inconveniente persiste, contacta a nuestro <a href="mailto:info@kotear.pe">Departamento de Atenci&oacute;n al Cliente</a>.</p>
      <br/>
    </div>
  </div>
  <blockquote>&nbsp;</blockquote>
  <blockquote>&nbsp;</blockquote>
  <blockquote>&nbsp;</blockquote>