<div class="container">
    <?php echo $this->action('busqueda','index', 'default');?>
    <h2 class="k-title mb10"><span></span>Bienvenido <?php echo $this->apodo?>!</h2>
    <p class="mb20">Ya estas habilitado para vender de la manera más fácil y rápida</p>
    <ul class="steps mb20">
      <li class="st1">Vender en <span class="hk1">KOTEAR</span> <span class="hk2">es FÁCIL!</span></li>
      <li class="line"></li>
      <li class="st2">
          <span class="number">1.</span>
          <span>Publica tu<br> aviso</span>
          <figure></figure>
      </li>
      <li class="line"></li>
      <li class="st3">
        <span class="number">2.</span>
        <span>Responde las<br> preguntas</span>
        <figure></figure>
      </li>
      <li class="line"></li>
      <li class="st4">
          <span class="number">3. </span>
          <span>Empieza a<br>
              recibir muchas<br>
              llamadas y mails</span>
          <figure></figure>
      </li>
    </ul>
    <p><span class="icon-footer-tip"></span><b>Nota:</b> Agrega el dominio <span class="red">@kotear.pe</span> en tu lista de correo segura, para poder recibir todos los mensajes de Kotear.pe en tu bandeja de entrada.</p>
</div> <!-- / register-confirm-email -->
