<?php echo $this->action('buscador','busqueda','default'); ?>
<div id="body-content" class="publish-pag pub-step5 col-master">
  <div id="s_level1" class="clearfix">
    <div class="col17">
      <h3>Aviso publicado</h3>
    </div>
  </div>
  <div id="s_level2" class="clearfix">
    <div id="left-bar" class="col17">
      <h3>¡Felicidades [Nombre de Vendeor]!</h3>
      <!-- COMIENZA CASO1-->
      <p>A continuación, te detallamos la información sobre tu publicación:</p>
      <p> Título del aviso: <a href="#">[asdf (3679659)]</a><br />
        Estado:  	 [Nuevo]<br />
        Unidades a la venta:  	 [1]<br />
        Precio final :  	 [<strong>S/.123,00</strong>]<br />
        Tipo de destaque:  	 [Nombre de destaque + (s/. MONTO DESTAQUE)  // si no ha elegido destaque igual debe aparecer Sin destaque (s/.0.00) </p>
      <!-- FIN CASO1-->
      <!-- COMIENZA CASO2-->
      <p>Estos son los detalles de tu aviso que ha sido activado posterior al pago del destaque que has realizado.</p>
      <p>Título del aviso: <a href="#">[asdf (3679659)]</a><br />
        Estado:  	 [Nuevo]<br />
        Unidades a la venta:  	 [1]<br />
        Precio final :  	 [<strong>S/.123,00</strong>]<br />
        Tipo de destaque:  	 [Nombre de destaque + (s/. MONTO DESTAQUE)  // si no ha elegido destaque igual debe aparecer Sin destaque (s/.0.00) </p>
      <!-- FIN CASO1-->
      <!-- COMIENZA CASO3-->
      <p>Estos son los detalles de tu aviso que se han activado. <strong>Recuerda</strong>, tienes 48 horas para cancelar el monto del destaque, de no hacerlo, tu aviso se desactivará y tu seras apercibido.</p>
      <p>Para cancelar el monto del destaque, entra a esta dirección:<br />
        <a href="http://kotear.pe/usuario/pagos">[http://kotear.pe/usuario/pagos]</a></p>
      <p> Título del aviso: <a href="#">[asdf (3679659)]</a><br />
        Estado:  	 [Nuevo]<br />
        Unidades a la venta:  	 [1]<br />
        Precio final :  	 [<strong>S/.123,00</strong>]<br />
        Tipo de destaque:  	 [Nombre de destaque(s/. MONTO DESTAQUE)  // si no ha elegido destaque igual debe aparecer Sin destaque (s/.0.00) </p>
      <!-- FIN CASO3-->
      <div class="datosvendedor">
        <p>La información de contacto que verá tu contraparte es la siguiente: <br>
          (Si esta información no fuera correcta, puedes modificarla ahora haciendo   <a href="#">clic aquí</a>).</p>
        <ul>
          <li>E-mail:  <span class="mail">erik.porroa@gmail.com</span></li>
          <li>Teléfono: 992775865 </li>
        </ul>
      </div>
      <div class="recomendaciones">
        <p><strong>Recomedaciones para vender mejor:</strong></p>
        <ul>
          <li>Revisa toda la información incluida en tu aviso; si encuentras algún error u omisión, es preferible que modifiques tu publicación ahora antes de que se registre una compra.</li>
          <li> Responde a todas las preguntas que te realicen los interesados en tu aviso; estar atento 
            a sus inquietudes te va a ayudar a cerrar rápidamente una venta.</li>
          <li>Sigue de cerca la venta desde la sección de &quot;Ventas Activas&quot; dentro de Mis Oportunidades</li>
        </ul>
      </div>
      <div class="lastbuttons">
        <ul>
          <li class="opt1"><a href="#">Publica otro aviso </a></li>
          <li class="opt2"><a href="#">Ver avisos</a></li>
        </ul>
      </div>
    </div>
    <div id="right-bar" class="last col5">
      <div class="block1 tip"></div>
    </div>
  </div>
  <div class="clear"></div>
</div>
<hr class="hide" />
