¡Felicidades Usuario
<div>Datos </div>
<div>A continuación te damos las opciones de como pagar este artículo</div>

<div>
  <div style="position:left">
    Datos de tu compra
    <div>
      <div style="position:left"><img src=""/></div>
      <div>Título</div>
    </div>
  </div>
  <div stype="position:right">
    <div></div>
  </div>

  A continuación te damos las opciones de como pagar este artículo
  JEEP GRAND CHEROKEE LAREDO 4X4S/DIVEMOTORS DUAL GLP 5TA GEN. 	JEEP GRAND CHEROKEE LAREDO 4X4S/DIVEMOTORS DUAL GLP 5TA GEN.
  Datos del vendedor
  Apodo: 	Montero2009 (0)  
  
  Nombre y apellido: 	Julio Ugarte
  Precio final: 	U$S 18500,00 		Teléfono: 	992999174
  Cantidad: 	1 		E-Mail: 	montero092009@hotmail.com
  Precio Total: 	U$S 18500,00 	  	Ubicación: 	Surco 
</div>
