
  <div id="body-content" class="miscalificaciones-pag col-master">
    <div id="s_level1" class="clearfix">
      <h3>Koteando (Mi Cuenta)</h3>
      <div id="account_navigation">
        <ul id="koteando_menu_secc">
          <li id="km_opt1"><a href="#">Mis Compras</a></li>
          <li id="km_opt2"><a href="#">Mis Ventas</a></li>
          <li id="km_opt3" class="active"><a href="#">Mis Calificaciones</a></li>
          <li id="km_opt4"><a href="#">Kotear Pagos</a></li>
          <li id="km_opt5"><a href="#">Mis Datos</a></li>
        </ul>
        <ul class="koteando_tabs_menu">
          <li><a href="#">Calificaciones Pendientes</a></li>
          <li class="active"><a href="#">Mi Reputación</a></li>
          <li><a href="#">Calificaciones realizadas</a></li>
        </ul>
        <ul class="koteando_rightmenu">
          <li><a href="#">Ayuda</a></li>
          <li><a href="#">Preguntas Frecuentes</a></li>
        </ul>
      </div>
      <div class="pagetitle col17">
        <h4>Calificar ahora</h4>
      </div>
    </div>
    <div id="s_level2" class="replicar clearfix">
      <!-- BORRAR : la clase puede cambiar de neutral a positivo o negativo según sea el caso -->
      <div class="neutral calificacion userinfo">
        <p class="c1">mensaje de pruebao</p>
        <p class="c2">Comprador:<br />
          <a href="#" class="az11">testuser (0)</a></p>
        <p class="c3">29/01/2010 12:47 hs:<br />
          <a href="#">canvas (3666465)</a></p>
      </div>
      <div class="positiva calificacion userinfo">
        <p class="c1">si, disculpa, el servicio fue bueno</p>
        <p class="c2">Comprador:<br />
          <a href="#" class="az11">testuser (0)</a></p>
        <p class="c3">29/01/2010 12:47 hs:<br />
          <a href="#">canvas (3666465)</a></p>
      </div>
      <div id="left-bar" class="col17">
        <form id="replicarfrm" name="replicarfrm" method="post" action="">
          <p class="block1 inpt"> <span class="title">Réplica:</span>
            <textarea name="comentario" rows="4" class="pdgr291"></textarea>
          </p>
          <div class="controls">
            <button type="submit" class="sbmt">Enviar</button>
            <button type="reset" class="cancel">Cancelar</button>
          </div>
        </form>
      </div>
      <div id="right-bar" class="last col5">
        <div class="block1 tip">
          <p>Presta atención a la redacción de la réplica. Ten en cuenta que lo que escribas lo va a leer toda la comunidad.</p>
        </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
  
  