<div id="account_navigation" class="clearfix">
  <?php //echo $this->action('menuSeccion', 'menu', 'usuario'); ?>
  <ul id="koteando_menu_secc">
    <!--<li id="km_opt1" class="active"><a href="<?php echo $this->baseUrl()?>/usuario/compra/historial-compras/opc/categoria/codigo/0">Mis Compras</a></li>
    <li id="km_opt2"><a href="<?php echo $this->baseUrl() ?>/usuario/venta/activas/opc/categoria/codigo/0">Mis Ventas</a></li>
    <li id="km_opt3"><a href="<?php echo $this->baseUrl() ?>/usuario/calificaciones/pendientes">Mis Calificaciones</a></li>-->
    <li id="km_opt4"><a href="<?php echo $this->baseUrl() ?>/pagos/index/pendiente-de-pago">Kotear Pagos</a></li>
    <li id="km_opt5"><a href="<?php echo $this->baseUrl()?>/usuario/edicion">Mis Datos</a></li>
  </ul>
  <ul class="koteando_tabs_menu">
    <!--<li class="<?php echo $class1; ?>"><a href="<?php echo $this->baseUrl()?>/usuario/compra/historial-compras/opc/categoria/codigo/0">Historial de Compras </a></li>-->
    <li class="<?php echo $class2; ?>"><a href="<?php echo $this->baseUrl() ?>/usuario/compra/preguntas-realizadas/opc/categoria/codigo/0">Preguntas Realizadas</a></li>
    <li class="<?php echo $class3; ?>"><a href="<?php echo $this->baseUrl()?>/usuario/compra/seguimiento">Compras en seguimiento</a></li>
  </ul>
  <!--
  <ul class="koteando_rightmenu">
    <li><a href="<?php echo$this->baseUrl() . '/construccion/'; ?>">Ayuda</a></li>
    <li><a href="<?php echo$this->baseUrl() . '/construccion/'; ?>">Preguntas Frecuentes</a></li>
  </ul>
  -->
</div>
