	
	  <div id="search">
	    <div class="content col-master">
	      <form id="searchfrm" class="prefix1" name="searchfrm" method="post" action="">
	        <h2 class="hide">Buscar</h2>
	        <p class="inpt">
	          <label for="lookingfor">Estoy buscando...
	            <input type="text" name="lookingfor" id="lookingfor" />
	          </label>
	        </p>
	        <p class="selc">
	          <label><span class="hide">En la categoria...</span>
	            <select name="categs" id="categs">
	              <option value="0">Todas las Categorias</option>
	            </select>
	          </label>
	        </p>
	        <p class="submt">
	          <button type="submit">Buscar</button>
	          <a href="#">Busqueda Avanzada</a></p>
	      </form>
	    </div>
	  </div>
	  <hr class="hide" />
	  <div id="body-content" class="miscompras-pag col-master">
	    <div id="s_level1" class="clearfix">
	      <h3>Koteando (Mi Cuenta)</h3>
	      <div id="account_navigation">
	        <ul id="koteando_menu_secc">
	          <li id="km_opt1" class="active"><a href="#">Mis Compras</a></li>
	          <li id="km_opt2"><a href="#">Mis Ventas</a></li>
	          <li id="km_opt3"><a href="#">Mis Calificaciones</a></li>
	          <li id="km_opt4"><a href="#">Kotear Pagos</a></li>
	          <li id="km_opt5"><a href="#">Mis Datos</a></li>
	        </ul>
	        <ul class="koteando_tabs_menu">
	          <li><a href="#">Historial de Compras</a></li>
	          <li><a href="#">Compras en Seguimiento</a></li>
	          <li class="active"><a href="#">Preguntas Realizadas</a></li>
	        </ul>
	        <ul class="koteando_rightmenu">
	          <li><a href="#">Ayuda</a></li>
	          <li><a href="#">Preguntas Frecuentes</a></li>
	        </ul>
	      </div>
	    </div>
	    <div class="pagetitle">
	      <h4>Preguntas Realizadas <span>(14 preguntas realizadas)</span></h4>
	      <ul class="labels">
	        <li class="pregunta_ico">Pregunta</li>
	        <li class="respuesta_ico">Respuesta</li>
	      </ul>
	    </div>
	    <div id="s_level2" class="clearfix">
	      <div id="left-bar" class="col5">
	        <ul class="box">
	          <li class="active">Cualquier Pregunta</li>
	          <li><a href="#">Preguntas No contestadas</a></li>
	          <li><a href="#"> Preguntas contestadas</a></li>
	        </ul>
	        <ul class="box">
	          <li class="active">Cualquier Categoría</li>
	          <li><a href="#">Informática</a></li>
	          <li><a href="#">Ropa y Accesorios</a></li>
	          <li><a href="#">Celulares, Telefonía y Faxes</a></li>
	          <li><a href="#">Deportes, Fitness y Aire Libre</a></li>
	        </ul>
	        <ul class="box">
	          <li class="active">Cualquier Fecha</li>
	          <li><a href="#">Ultima semana</a></li>
	          <li><a href="#"> Ultimo mes</a></li>
	        </ul>
	      </div>
	      <div id="right-bar" class="col17 last">
	        <table border="0" cellspacing="0" cellpadding="0">
	          <thead>
	            <tr>
	              <td class="subtitle">Informática</td>
	              <td>2 preguntas realizadas</td>
	            </tr>
	          </thead>
	          <tbody>
	            <tr>
	              <td class="pic"><img src="<?=$this->baseUrl() ?>/img/global/img_placer_75.gif" width="75" height="75" alt="foto" /></td>
	              <td><p><a href="#">Funda de Silicona Lg KU990 / KE990 Viewty skin</a></p>
	                <p>Realizada el 21/09/2008 00:09 hs.</p>
	                <p>Vendedor: <a class="granvendedor badge seller" href="#">PERUACCESORIOS (229)</a></p>
	                <p class="pregunta">Hola: solo tienes 5 unidades de stock? Eres fabricante?</p>
	                <p class="respuesta">no tengo mucho mas,no soy fabricante cuantos deseas tu? confirmame,o compra para poder hablar Gracias</p></td>
	            </tr>
	            <tr>
	              <td class="pic"><img src="<?=$this->baseUrl() ?>/img/global/img_placer_75.gif" width="75" height="75" alt="foto" /></td>
	              <td><p><a href="#">Funda de Silicona Lg KU990 / KE990 Viewty skin</a></p>
	                <p>Realizada el 21/09/2008 00:09 hs.</p>
	                <p>Comprador: <a class="seller" href="#">gian_111 (0)</a></p>
	                <p class="pregunta">Hola: solo tienes 5 unidades de stock? Eres fabricante?</p></td>
	            </tr>
	          </tbody>
	        </table>
	        <table border="0" cellspacing="0" cellpadding="0">
	          <thead>
	            <tr>
	              <td class="subtitle">Ropa y Accesorios</td>
	              <td>3 preguntas realizadas</td>
	            </tr>
	          </thead>
	          <tbody>
	            <tr>
	              <td class="pic"><img src="<?=$this->baseUrl() ?>/img/global/img_placer_75.gif" width="75" height="75" alt="foto" /></td>
	              <td><p><a href="#">Funda de Silicona Lg KU990 / KE990 Viewty skin</a></p>
	                <p>Realizada el 21/09/2008 00:09 hs.</p>
	                <p>Vendedor: <a class="granvendedor badge seller" href="#">PERUACCESORIOS (229)</a></p>
	                <p class="pregunta">Hola: solo tienes 5 unidades de stock? Eres fabricante?</p>
	                <p class="respuesta">no tengo mucho mas,no soy fabricante cuantos deseas tu? confirmame,o compra para poder hablar Gracias</p></td>
	            </tr>
	            <tr>
	              <td class="pic"><img src="<?=$this->baseUrl() ?>/img/global/img_placer_75.gif" width="75" height="75" alt="foto" /></td>
	              <td><p><a href="#">Funda de Silicona Lg KU990 / KE990 Viewty skin</a></p>
	                <p>Realizada el 21/09/2008 00:09 hs.</p>
	                <p>Comprador: <a class="seller" href="#">gian_111 (0)</a></p>
	                <p class="pregunta">Hola: solo tienes 5 unidades de stock? Eres fabricante?</p>
	                <p class="respuesta">no tengo mucho mas,no soy fabricante cuantos deseas tu? confirmame,o compra para poder hablar Gracias</p></td>
	            </tr>
	            <tr>
	              <td class="pic"><img src="<?=$this->baseUrl() ?>/img/global/img_placer_75.gif" width="75" height="75" alt="foto" /></td>
	              <td><p><a href="#">Funda de Silicona Lg KU990 / KE990 Viewty skin</a></p>
	                <p>Realizada el 21/09/2008 00:09 hs.</p>
	                <p>Comprador: <a class="seller" href="#">gian_111 (0)</a></p>
	                <p class="pregunta">Hola: solo tienes 5 unidades de stock? Eres fabricante?</p></td>
	            </tr>
	          </tbody>
	        </table>
	      </div>
	    </div>
	    <div class="clear"></div>
	  </div>
	  <hr class="hide" />
	  