<form name="form" id="form" >

    <div align="center" id="body-content" class="product-pag col-master">
        <div style="width: 500px; border:  solid 2px #C5C5C6; background: #E9E9E9; padding: 10px;">
            <div style="font-size: 20px; height: 80px; padding-top: 10px;">

            <label  >
                    Su compra fue exitosa

            </label>

                 </div>
<p>
            <a class="btn_submit sep_left" href="<?php echo $this->baseUrl()?>/pagos/index/" >Volver</a>
        </div>



    </div>
</form>