<div class="pasarela-ok container">
    <h2 class="k-title mb10"><span></span>Confirmaci&oacute;n de pasarela</h2>
    <div class="message-gateway">
        <h3>¡<?=!empty($this->msgerror)?'Lo sentimos, no se pudo procesar la operación':'Proceso satisfactorio'?>!</h3>
        <p>Hemos recibido el pago de tu operación por Pasarela con los siguientes datos</p>
          <div class="form-horizontal">
              <div class="control-group first">
                  <label class="control-label"><strong>Medio de Pago:</strong></label>
                      <div class="controls"><?=$this->medioPago?></div>
              </div>
              <div class="control-group">
                  <label class="control-label"><strong>Transacción:</strong></label>
                      <div class="controls"><?=$this->idTransaccion?></div>
              </div>
              <div class="control-group">
                  <label class="control-label"><strong>Monto:</strong></label>
                      <div class="controls"><?=$this->monto?></div>
              </div>
              <div class="control-group">
                  <label class="control-label"><strong>Fecha de la operación:</strong></label>
                      <div class="controls"><?=$this->fechaPasarela?></div>
              </div>
              <?php if(!empty($this->msgerror)){ ?>
              <div class="control-group">
                      <label class="control-label"><strong>Motivo:</strong></label>
                      <div class="controls"><?=$this->msgerror?></div>
              </div>
              <?php } ?>
              <div class="control">
                     <a class="btn-kotear" href="<?=$this->baseUrl()?>/usuario/venta/pendiente-pago">Volver</a>
               </div>
          </div>
            </div>
</div>
