<form name="form" id="form" >

    <div align="center" id="body-content" class="product-pag col-master">
        <div style="width: 500px; border:  solid 2px #C5C5C6; background: #E9E9E9; padding: 10px;">
            <div style="font-size: 20px; height: 40px; padding-top: 10px;">
            <label  >
                    Codigo de pago
            </label>

                 </div>
            <div style="font-size: 30px;    ">
                2333323234234

            </div>
            <a class="btn_submit sep_left" href="<?php echo $this->baseUrl()?>/pagos/index/" >Volver</a>
        </div>



    </div>
</form>