<!--<head>
  <title>Kotear.pe Comprar y Vender en Perú</title>  
</head>-->
<body>
   <style>
  * { margin:0; padding:0; }
  body { background:url(../img/bg-body.png) repeat-x; }
  #wrapper { width:980px; height:800px; margin:0 auto; }
  #wrapper img { width:980px; height:800px; float:left; }
  </style>
    <div id="wrapper">
        <img src="../img/kotear.jpg" alt="Kotear.pe" width="980" height="800" usemap="#Map" border="0" />
        <map name="Map">
          <area shape="poly" coords="979,35,979,54,975,58,864,58,860,54,860,35,864,31,975,31" target="_blank" href="http://kotear.clasificados.pe/" alt="Kotear.pe" title="Kotear.pe">
          <area shape="poly" coords="51,703,62,690,915,690,929,703,930,755,914,768,64,768,50,754" href="http://kotear.clasificados.pe/usuario/acceso" target="_blank" alt="Publica tu aviso" title="Publica tu aviso">
        </map>
    </div>
</body>

