 <div id="body-content" class="miscalificaciones-pag col-master">
    <div id="s_level1" class="clearfix">
      <h3>Koteando (Mi Cuenta)</h3>
<!--      <div id="account_navigation">
        <ul id="koteando_menu_secc">
          <li id="km_opt1"><a href="#">Mis Compras</a></li>
          <li id="km_opt2"><a href="#">Mis Ventas</a></li>
          <li id="km_opt3" class="active"><a href="#">Mis Calificaciones</a></li>
          <li id="km_opt4"><a href="#">Kotear Pagos</a></li>
          <li id="km_opt5"><a href="#">Mis Datos</a></li>
        </ul>
        <ul class="koteando_tabs_menu">
          <li><a href="#">Calificaciones Pendientes</a></li>
          <li class="active"><a href="#">Mi Reputación</a></li>
          <li><a href="#">Calificaciones realizadas</a></li>
        </ul>
        <ul class="koteando_rightmenu">
          <li><a href="#">Ayuda</a></li>
          <li><a href="#">Preguntas Frecuentes</a></li>
        </ul>
      </div>
-->
<?php echo $this->action('navegacion','menu','default', array('nav'=>'calificacion', 'opc'=>2));?>

      <div class="pagetitle col17">
        <h4>Calificar ahora</h4>
      </div>
    </div>
    <div id="s_level2" class="replicar clearfix">
      <div id="left-bar" class="col17">
      <?php echo $this->codigo?>
	Su respuesta fue guardada, se le esta enviando un email.
    
      </div>
      <div id="right-bar" class="last col5">
        <div class="block1 tip">
          <p>Presta atención a la redacción de la réplica. Ten en cuenta que lo que escribas lo va a leer toda la comunidad.</p>
        </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>