<div id="account_navigation" class="clearfix">
  <ul id="koteando_menu_secc">
    <li id="km_opt1"><a href="<?php echo $this->baseUrl() ?>/usuario/compra/historial-compras/opc/categoria/codigo/0">Mis Compras</a></li>
    <li id="km_opt2" class="active"><a href="<?php echo $this->baseUrl() ?>/usuario/venta/activas/opc/categoria/codigo/0">Mis Ventas</a></li>
    <li id="km_opt3"><a href="<?php echo $this->baseUrl() ?>/usuario/calificaciones/pendientes">Mis Calificaciones</a></li>
    <li id="km_opt4"><a href="<?php echo $this->baseUrl() ?>/pagos/index/pendiente-de-pago">Kotear Pagos</a></li>
    <li id="km_opt5"><a href="<?php echo $this->baseUrl()?>/usuario/edicion">Mis Datos</a></li>
  </ul>
  <ul class="koteando_tabs_menu">

    <li class="<?php echo $active1 ?>" ><a href="<?php echo $this->baseUrl() ?>/usuario/venta/activas/opc/categoria/codigo/0">Avisos Activos</a></li>
    <li class="<?php echo $active2 ?>"><a href="<?php echo $this->baseUrl() ?>/usuario/venta/inactivas/opc/categoria/codigo/0">Avisos no Activos</a></li>
    <!--<li class="<?php echo $active3 ?>"><a href="<?php echo $this->baseUrl() ?>/usuario/venta/historial">Historial de Ventas</a></li>-->
    <!--<li class="<?php echo $active3 ?>"><a href="<?php echo $this->baseUrl() ?>/usuario/venta/historial-ventas/opc/categoria/codigo/0">Historial de Ventas</a></li>-->
    <li class="<?php echo $active4 ?>"><a href="<?php echo$this->baseUrl() ?>/usuario/venta/preguntas-recibidas/opc/categoria/codigo/0">Preguntas Recibidas</a></li>
  </ul>
  <!--
  <ul class="koteando_rightmenu">
    <li><a href="#">Ayuda</a></li>
    <li><a href="#">Preguntas Frecuentes</a></li>
  </ul>
  -->
</div>
