<?php
//header("Content-Type: application/rss+xml; charset=utf-8");
//header("Content-Type: application/rss+xml");
echo "<?xml version='1.0' encoding='UTF-8'?> "
      ."<rss version='2.0' xmlns:atom='http://www.w3.org/2005/Atom'>"
      ."<channel>"
        ."<title><![CDATA[Kotear - Suscripcion a RSS]]></title>"
        ."<link><![CDATA[http://www.kotear.pe]]></link>"
        ."<description><![CDATA[Kotear - Donde compras y vendes de todo]]></description>"
        ."<language>es-es</language>"
        ."<copyright><![CDATA[Kotear]]></copyright>"
        ."<atom:link href='http://kotear.pe/feed/rss' rel='self' type='application/rss+xml' />";

foreach($this->avisos as $r){
    $href = $this->baseUrl() . '/aviso/' . $r->ID_AVISO . '-' .$r->URL;
              if ($r->FOTO == 1) { $img = $this->rutaimagen . $r->IMAGEN; }
              else { $img = $this->rutaimagen . 'none.gif'; }
  echo '<item>
        <title>'.$r->TIT.'</title>
        <link>'. $href.'</link>
        <description>
        &lt;table&gt;
            &lt;tr&gt;
            
                &lt;td&gt;
                    &lt;img src="'.$img.'" &gt;
                &lt;/td&gt;

                &lt;td&gt;
                 &lt;table&gt;
                    &lt;tr&gt; &lt;td&gt; &lt;a  href="'. $this->baseUrl() . '/usuario/reputacion/ver/cod/' . $r->ID_USR.'"&gt;'.$r->APODO.'('.$r->PUNTAJE.')&lt;/a&gt; &lt;/td&gt; &lt;/tr&gt;
                    &lt;tr&gt; &lt;td&gt; Caduca: ' .$r->CADUCIDAD. '&lt;/td&gt; &lt;/tr&gt;
                    &lt;tr&gt; &lt;td&gt; Precio: ' . $r->SIMB . ' ' . $r->PRECIO . '&lt;/td&gt; &lt;/tr&gt;
                    &lt;tr&gt; &lt;td&gt; Ofertas: ' . $r->NUM_OFERTAS . '&lt;/td&gt; &lt;/tr&gt;
                &lt;/table&gt;
               &lt;/td&gt;
               
            &lt;/tr&gt;
        &lt;/table&gt;
</description>
        </item>
';
}
echo "</channel>"
        ."</rss>";

?>