<div isData="<?=$this->isData?>" msg="<?=$this->msg?>">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 id="myModalLabel">Editar</h4>
    </div>
    <div class="modal-body">
        <?=$this->form?>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        <button id="abtnGuardar" class="btn btn-primary abtnGuardar">Guardar</button>
    </div>
</div>