<?php 
if (count($this->data)>0) { ?>
<div >
    <table class="fbTable table table-bordered table-striped">
        <thead >
            <tr>
                <th ></th>
                <th >Apodo</th>
                <th >E-mail</th>
                <th >Clave</th>
                <th >Num. Doc</th>
                <th >Tipo Usuario</th>
            </tr>
        </thead>
        <tbody>
        <?php
            $class = array(0 => 'even', 1 => '');
            $i = 0;
            foreach ($this->data as $data) : 
        ?>
                <tr class="<?= $class[$i++ % 2] ?>">
                    <td class="headAccion">
                        <a href="javascript:;" class="apfbBtnOpenModal"
                           data-id="<?=$this->escape($data->ID_USR)?>">
                            <img src="<?= URL_STATIC . 'img/admin/pencil.png'?>" width="12" height="12"/>
                        </a>
                    </td>
                    <td ><?= $this->escape($data->APODO) ?></td>
                    <td ><?= $this->escape($data->EMAIL) ?></td>
                    <td ><?= $this->escape($data->CLAVE) ?></td>
                    <td ><?= $this->escape($data->NRO_DOC) ?></td>
                    <td ><?= $this->escape($data->DES) ?></td>
                </tr>
        <?  endforeach; ?>
        </tbody>
    </table>
</div>
<div class="fbPagination">
    <?= $this->paginationControl($this->paginador, 'Sliding', '_partials/_pag.phtml') ?>
</div>
<?php } else { ?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>No hay datos registrados con esos parámetros.</strong>
    </div>
<?php } ?>