<div class="container">
        <?php echo $this->action('busqueda','index','default'); ?>
        <h3 class="k-title"><span></span>Cambio de e-mail</h3>
        <div class="message-finish">
            <h4>Validación de nuevo e-mail de contacto </h4>
            <p>La dirección de correo quedó registrada.</p>
            <p>
              <a href="<?php echo $this->baseUrl()?>">IR A LA PAGINA PRINCIPAL</a>
            </p>
        </div>
</div>