<!--Pregunta Completa-->
<div id="body-content" class="regform-pag col-master">
<h1 class="title">Preguntas al Vendedor</h1>
<center>Tu pregunta ha sido realizada con éxito.</center>
<center>Te informaremos a tu mail de contacto cuando el vendedor haya respondido.</center>
<center><input type="button" class="redbutton" value="Volver" onclick="window.location.href='<?=$this->volver?>'"/></center>

</div>
