<!DOCTYPE html>
<!--[if lt IE 7]><html xmlns:fb="http://ogp.me/ns/fb#" class="no-js lt-ie lt-ie9 lt-ie8 lt-ie7" lang="es" itemtype="http://schema.org/WebPage" itemscope="itemscope"><![endif]-->
<!--[if IE 7]><html xmlns:fb="http://ogp.me/ns/fb#" class="no-js lt-ie lt-ie9 lt-ie8" lang="es" itemtype="http://schema.org/WebPage" itemscope="itemscope"><![endif]-->
<!--[if IE 8]><html xmlns:fb="http://ogp.me/ns/fb#" class="no-js lt-ie lt-ie9" lang="es" itemtype="http://schema.org/WebPage" itemscope="itemscope"><![endif]-->
<!--[if gt IE 8]><!--><html xmlns:fb="http://ogp.me/ns/fb#" class="no-js lt-ie" lang="es" itemtype="http://schema.org/WebPage" itemscope="itemscope"><!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="google-site-verification" content="0ZWsiCvjZvsOUeRcUtV5PgTeUzDHpmXg0USJH1LBH-o" />
    <?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    if($controller=='registro'){ ?>
    <meta name="ROBOTS" CONTENT="NOINDEX" />
    <meta name="robots" content="noimageindex"/>
    <?php } else{  ?>
    <meta name="robots" content="index,follow"/>
    <?php } ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <meta name="description" content="¿Quieres comprar o quieres vender en el Perú?, Kotear te ofrece el mejor espacio de compra y venta de productos y servicios, Anuncia Gratis en Kotear.clasificados.pe" />
    <meta name="keywords" content="Comprar en Peru, Vender en Peru, compra y venta de productos y servicios clasificados peru. anuncio gratis, clasificados en el peru" />
    <meta name="title" content="Comprar y Vender en el Perú. Anuncios de Productos y Servicios en el Perú | Kotear.clasificados.pe"/>
    <meta name="author" content="kotear.clasificados.pe"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="language" content="es"/>
    <meta name="geo.region" content="PE-LIM"/>
    <meta name="geo.placename" content="Cercado de Lima"/>
    <meta name="geo.position" content="-12.0478;-77.0622"/>
    <meta name="ICBM" content="-12.0478, -77.0622"/>
    <meta name="DC.Title" content="Comprar y Vender en el Perú. Anuncios de Productos y Servicios en el Perú | Kotear.clasificados.pe"/>
    <meta name="DC.Creator" content="http://kotear.pe"/>
    <meta name="DC.Description" content="¿Quieres comprar  o quieres vender en el Perú?, Kotear te ofrece el mejor espacio de compra y venta de productos y servicios, Anuncia Gratis en Kotear.clasificados.pe"/>
    <meta name="DC.Publisher" content="Kotear"/>
    <meta name="DC.Language" content="es"/>
    <meta property="og:site_name" content="Kotear" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="http://kotear.pe" />
    <meta property="og:title" content="Comprar y Vender en el Perú. Anuncios de Productos y Servicios en el Perú | Kotear.clasificados.pe"/>
    <meta property="og:description" content="¿Quieres comprar  o quieres vender en el Perú?, Kotear te ofrece el mejor espacio de compra y venta de productos y servicios, Anuncia Gratis en Kotear.clasificados.pe"/>
    <meta property="og:image" content="<?=URL_STATIC?>img/logo.jpg<?php echo App_Config::getStaticVersion(); ?>"/>
    <link href="<?=URL_STATIC?>img/logo.jpg<?php echo App_Config::getStaticVersion(); ?>" rel="image_src" type="image/jpeg"/>
    <link href="<?=URL_STATIC?>img/favicon.ico<?php echo App_Config::getStaticVersion(); ?>" rel="icon" type="image/vnd.microsoft.icon"/>
    <link href="<?=URL_STATIC?>img/favicon.ico<?php echo App_Config::getStaticVersion(); ?>" rel="shortcut icon" type="image/x-icon"/>
    <!--[if lt IE 9]><script type="text/javascript" src="<?=URL_STATIC?>js/libs/html5shiv.js<?php echo App_Config::getStaticVersion(); ?>"></script><![endif]-->
    <?= $this->yoson; ?>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-28124903-1']);
        _gaq.push(['_setDomainName', 'clasificados.pe']);
        _gaq.push(['_trackPageview']);
        _gaq.push(['_trackPageLoadTime']);
        (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="home">
    <div class="top-gec">
        <div class="wpage-gec">
            <div class="left-gec">
                <a title="Grupo El Comercio" href="http://elcomercio.pe" target="_blank" class="logo-gec"></a>
                <h4 class="clasificados-gec">Los clasificados de compra y venta de El Comercio</h4>
            </div>
            <div itemscope="itemscope" itemtype="http://schema.org/Organization" class="right-gec">
                <div class="head-gec">
                    <span class="part-of-gec-lupa"></span>
                    <span class="part-of-gec">Parte de </span>
                    <a href="http://clasificados.pe/?ref=kotear" target="_blank" itemprop="name" title="Clasificados.pe"  class="link-gec" id="link-gec-arrow">Clasificados.pe</a>
                </div>
                <div class="body-gec">
                    <ul id="slide-gec">
                        <li itemscope="itemscope" itemtype="http://schema.org/Organization" class="first-gec">
                            <span itemprop="member" class="title-gec">Empleos</span>
                            <a href="http://aptitus.clasificados.pe/?ref=kotear" title="Aptitus.pe" target="_blank" itemprop="url" class="main-link-gec">Aptitus.pe</a>
                        </li>
                        <li itemscope="itemscope" itemtype="http://schema.org/Organization">
                            <span itemprop="member" class="title-gec">Inmuebles y propiedades</span>
                            <a href="http://urbania.clasificados.pe/?ref=kotear" title="Urbania.pe" target="_blank" itemprop="url" class="main-link-gec">Urbania.pe</a>
                        </li>
                        <li itemscope="itemscope" itemtype="http://schema.org/Organization">
                            <span itemprop="member" class="title-gec">Autos y motos</span>
                            <a href="http://neoauto.clasificados.pe/?ref=kotear" title="Neoauto.pe" target="_blank" itemprop="url" class="main-link-gec">Neoauto.pe</a>
                        </li>
                        <li itemscope="itemscope" itemtype="http://schema.org/Organization">
                            <span itemprop="member" class="title-gec">Comprar y vender</span>
                            <a href="http://kotear.clasificados.pe/?ref=kotear" title="Kotear.pe" target="_blank" itemprop="url" class="main-link-gec">Kotear.pe</a>
                        </li>
                        <li itemscope="itemscope" itemtype="http://schema.org/Organization">
                            <span itemprop="member" class="title-gec">Micro y peque&ntilde;as empresas</span>
                            <a href="http://nuestromercado.clasificados.pe/?ref=kotear" title="NuestroMercado.pe" target="_blank" itemprop="url" class="main-link-gec">NuestroMercado.pe</a>
                        </li>
                        <li itemscope="itemscope" itemtype="http://schema.org/Organization" class="last-gec">
                            <span itemprop="member" class="title-gec">Restaurantes y caf&eacute;s</span>
                            <a href="http://guiagps.clasificados.pe/restaurantes?ref=kotear" title="GPSRestaurantes.pe" target="_blank" itemprop="url" class="main-link-gec">GPSRestaurantes.pe</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->mediakit;
echo $this->dax; ?>
<?php echo $this->clickTale;
echo $this->ClickTale_Top; ?>
    <div id="wrapper">
        <div class="banner"><?php echo '<script type="text/javascript">eplAD4("Top"); </script>'; ?></div>
        <header>
            <h1 itemscope="itemscope" itemtype="http://schema.org/Organization">
                <a href="<?php echo $this->baseUrl(); ?>" title="kotear.clasificados.pe" itemprop="url">
                    <img itemprop="image" alt="<?php echo $this->baseUrl(); ?>" src="<?=URL_STATIC?>img/logo.jpg<?php echo App_Config::getStaticVersion(); ?>" width="271" height="84"/>
                </a>
                <meta itemprop="name" content="kotear.pe"/>
            </h1>
            <div class="log-in">
                <ul class="options">
                    <?php if(!isset($this->identity)){; ?>
                    <li>
                        <a id="log-in" href="<?php echo $this->baseUrl(); ?>/usuario/acceso/ingresar" title="Ingresa">Ingresa</a>
                    </li>                
                    <li class="break">|</li>
                    <li>
                        <a id="sign-in" href="<?php echo $this->baseUrl(); ?>/usuario/registro" title="Registrate">Registrate</a>
                    </li>
                    <?php } else { ?>
                    <li>
                        <a href="<?php echo $this->baseUrl(); ?>/usuario/cuenta" title="Ir a la cuenta de <?php echo $this->identity->APODO; ?>"><?php echo $this->identity->APODO; ?></a>
                    </li>            
                    <li class="break">|</li>        
                    <li>
                        <a class="user_state_session_on" href="<?php echo $this->baseUrl(); ?>/usuario/acceso/logout" title="Terminar sesión">Salir</a>
                    </li>
                    <?php } ?>
                </ul>
                <div class="button-publicity">
                    <p>¿Quieres incrementar tus ventas?</p>
                    <a href="<?php echo $this->baseUrl(); ?>/usuario/publicacion/registro-destaque" title="Publica tu aviso Aqui">Publica tu aviso AQUI!</a>
                </div>
            </div>
        </header>    
        <nav class="menu-general">        
            <ul class="c-nav">
                <li class="hover-star">
                    <a href="<?=$this->baseUrl()?>" title="Inicio">inicio</a>
                </li>
                <li class="line"></li>
                <li>
                    <a href="<?=$this->baseUrl()?>/usuario/publicacion/registro-destaque" title="Publica tu aviso">publica tu aviso</a>
                </li>
                <li class="line"></li>
                <li>
                    <a href="<?=$this->baseUrl()?>/usuario/cuenta" title="Mi Cuenta">mi cuenta</a>
                </li>
                <li class="line"></li>
                <li>
                    <a href="http://centraldeayuda.kotear.pe/entries/21701048-que-es-kotear-pe" title="Qué es Kotear?" target="_blank">¿qué es kotear?</a>
                </li>
            </ul>
            <ul class="social-links">
                <li>
                    <a href="https://www.facebook.com/koteando" target="_blank" title="Facebook" class="link-facebook"></a>
                </li>
                <li>
                    <a href="https://twitter.com/koteando" target="_blank" title="Twitter" class="link-twitter"></a>
                </li>
            </ul>
        </nav>
<?php /* <!--          INICIO          --> */ ?>
        <?=$this->layout()->content?>
<?php /* <!--          FIN             -->   */?>
        <footer class="row">
            <?=$this->action('footer','ap-layout', 'default');?>
        </footer>
        <div class="means-of-payment">
            <div class="buy-insurance">
                <span>Pagos 100% seguros con:&nbsp;</span>
                    <a href="https://pagoefectivo.pe/" title="PagoEfectivo" target="_blank" class="ico-pefectivo"></a>
                    <a href="http://www.visanet.com.pe/" title="Visa" target="_blank" class="ico-visa"></a>
                    <a href="javascript:;" title="Verified by Visa" class="ico-vrvisa verified-by-visa-ico"></a>
                    <a href="http://www.mastercard.com/pe/gateway.html" title="Mastercard" target="_blank" class="ico-mastercard"></a>
                    <a href="http://www.mastercard.com/us/personal/es/servicios/codigodeseguridad/" title="Mastercard Securecode" target="_blank" class="ico-smastercard"></a>
                    <a href="http://www.visanet.com.pe/promovbv/bancos.html" title="Afiliate a Verified by Visa" target="_blank" class="ico-afvisa"></a>
            </div>
            <div class="buy-detail">
                <p>Autorizados por Visa para realizar transacciones electrónicas</p>
            </div>
            <div class="shadow-space"></div>
            <ul class="copyright">
                <li class="copyright-link">&copy; <?php echo date ("Y" );?> Kotear.pe</li>
                <li>
                    <a href="http://centraldeayuda.kotear.pe/entries/21701048-que-es-kotear-pe" title="Acerca de kotear" target="_blank">Acerca de kotear</a>
                </li>
                <li>
                    <a href="http://centraldeayuda.kotear.pe/home" title="Ayuda" target="_blank">Ayuda</a>
                </li>
                <li>
                    <a href="http://centraldeayuda.kotear.pe/entries/21772626-terminos-y-condiciones" title="Términos de Uso" target="_blank">Términos de Uso</a>
                </li>
                <li>
                    <a href="http://centraldeayuda.kotear.pe/entries/21750101-politicas-de-privacidad-y-confidencialidad-de-la-informacion" title="Política de Privacidad" target="_blank">Política de Privacidad</a>
                </li>
                <li>
                    <a href="http://gec.pe/LibroReclamaciones/hojareclamo.aspx?Medio=kotear" title="Libro de reclamaciones" class="complaints-book" target="_blank"><span></span>Libro de reclamaciones</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="see-also">
        <div class="box-center">
            <span>Visite también:</span>
            <ul>
                <li>
                    <a href="http://elcomercio.pe?ref=kotear" title="Diario el Comercio" target="_blank">elcomercio.pe</a>
                </li>
                <li>
                    <a href="http://peru.com?ref=kotear" title="Peru.com" target="_blank">peru.com</a>
                </li>
                <li>
                    <a href="http://peru21.pe?ref=kotear" title="Diario Perú21" target="_blank">peru21.pe</a>
                </li>
                <li>
                    <a href="http://laprensa.com.pe?ref=kotear" title="La Prensa" target="_blank">laprensa.com.pe</a>
                </li>
                <li>
                    <a href="http://gestion.pe?ref=kotear" title="Diario Gestión" target="_blank">gestion.pe</a>
                </li>
                <li>
                    <a href="http://depor.pe?ref=kotear" title="Depor.pe" target="_blank">depor.pe</a>
                </li>
                <li>
                    <a href="http://trome.pe?ref=kotear" title="Diario Trome" target="_blank">trome.pe</a>
                </li>
                <li>
                    <a href="http://publimetro.pe?ref=kotear" title="Publimetro" target="_blank">publimetro.pe</a>
                </li>
                <li>
                    <a href="http://gec.pe?ref=kotear" title="GEC" target="_blank">gec.pe</a>
                </li>
                <li class="last">
                    <a href="http://clasificados.pe?ref=kotear" title="Clasificados.pe" target="_blank">clasificados.pe</a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="http://aptitus.pe?ref=kotear" title="Aptitus" target="_blank">aptitus.pe</a>
                </li>
                <li>
                    <a href="http://urbania.pe?ref=kotear" title="Urbania" target="_blank">urbania.pe</a>
                </li>
                <li>
                    <a href="http://neoauto.pe?ref=kotear" title="Neoauto" target="_blank">neoauto.pe</a>
                </li>
                <li>
                    <a href="http://guiagps.pe?ref=kotear" title="GuiaGPS" target="_blank">guiagps.pe</a>
                </li>
                <li>
                    <a href="http://ofertop.pe?ref=kotear" title="Ofertop" target="_blank">ofertop.pe</a>
                </li>
                <li>
                    <a href="http://nuestromercado.pe?ref=kotear" title="NuestroMercado" target="_blank">nuestromercado.pe</a>
                </li>
                <li>
                    <a href="http://pagoefectivo.pe?ref=kotear" title="PagoEfectivo" target="_blank">pagoefectivo.pe</a>
                </li>
                <li>
                    <a href="http://clubsuscriptores.pe?ref=kotear" title="Club de Suscriptores" target="_blank">clubsuscriptores.pe</a>
                </li>
                <li class="last">
                    <a href="http://perured.pe?ref=kotear" title="PeruRed" target="_blank">perured.pe</a>
                </li>
            </ul>
        </div>
    </div>
<?php /* <!--Yoson--> */ ?>
    <?php $m = Zend_Controller_Action_HelperBroker::getStaticHelper('Redirector')->getRequest()->getModuleName(); ?>
    <script src="<?=URL_STATIC?>js/libs/framework.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <script src="<?=URL_STATIC?>js/application/yoson.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <script src="<?=URL_STATIC?>js/application/schemas/requires.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <?php if($m!="pagos" && $m!="servicio"){ ?>
    <script src="<?=URL_STATIC?>js/modules/<?php echo $m; ?>.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <?php } ?>
    <script src="<?=URL_STATIC?>js/modules/all-modules.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <script src="<?=URL_STATIC?>js/application/schemas/modules.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <script src="<?=URL_STATIC?>js/appLoad.js<?php echo App_Config::getStaticVersion(); ?>" type="text/javascript"></script>
    <?php /* <!-- Begin DAX de Kotear --> */?>
    <script type="text/javascript" language="JavaScript1.3" src="http://b.scorecardresearch.com/c2/6906602/ct.js"></script>
    <?php /* <!-- Fin DAX de Kotear --> */?>
    <?php 
    echo $this->scCXSearch;
    echo $this->ClickTale_Bottom;?>
    <?php /* <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>  */?>
    <?php echo $this->headScript(); ?>
</body>
</html>