<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Vista de Impresion | Kotear.pe</title>

<link href="<?php echo $this->baseUrl()?>/f/css/grids.css" rel="stylesheet" type="text/css" media="all" />
<link href="<?php echo $this->baseUrl()?>/f/css/print.product.css" rel="stylesheet" type="text/css" media="all" />

</head>
<body class="home" onload = 'window.print()'>
<div id="wrapper">
  <div id="body-content" class="col-master">
    
    <div>

    <?php echo $this->layout()->content; ?>

    </div>
    <div class="clear"></div>
  </div>
</div>

</body>
</html>