
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
  <title>Vista de Impresion | Kotear.pe</title>
  <link type="text/css" rel="stylesheet" href="<?=URL_STATIC?>css/style.css?id=10" media="all"/>
</head>

<body class="impress" onload = 'window.print()'>
	<?php echo $this->layout()->content; ?>
</body>
</html>