<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Vista de Impresion | Kotear.pe</title>

        <link href="<?=URL_STATIC?>css/grids.css" rel="stylesheet" type="text/css" media="all" />
        <link href="<?=URL_STATIC?>css/print.css" rel="stylesheet" type="text/css" media="all" />
        <style type="text/css">
            img { float: none; margin: 1em 1.5em 1.5em 0; }
            td {
border-bottom:0 solid #333333;
}
        </style>
    </head>
    <body class="home" onload = 'window.print()'>
        <div id="wrapper">
            <div id="body-content" class="col-master" >
                <table border="0" width="100%">
                    <tr border="0">
                        <td><h1>CREDIPAGO - PAGOEFECTIVO</h1></td>
                        <td width="15%"><img src="<?php echo $this->baseUrl() ?>/img/global/logo_pe.png"/></td>
                    </tr>
                </table>
                <div>

                    <?php echo $this->layout()->content; ?>

                </div>
                <div class="clear"></div>
            </div>
        </div>

    </body>
</html>