<!--buscador-->
<div id="search">
        <div class="content col-master">
        <form id="searchfrm" class="prefix1" name="searchfrm" method="post" action="">
            <h2 class="hide">Buscar</h2>
            <p class="inpt">
            <label for="lookingfor">Estoy buscando...
                <input type="text" name="lookingfor" id="lookingfor" />
            </label>
            </p>
            <p class="selc">
            <label><span class="hide">En la categoria...</span>
                <select name="categs" id="categs">
                <option value="0">Todas las Categorias</option>
                </select>
            </label>
            </p>
            <p class="submt">
            <button type="submit">Buscar</button>
            <a href="#">Búsqueda Avanzada</a></p>
        </form>
        </div>
    </div>
    <hr class="hide" />