 <div id="account_navigation">
        <ul id="koteando_menu_secc">
          <li id="km_opt1" class="active"><a href="<?php $this->baseUrl()?>/usuario/compra/historialcompras">Mis Compras</a></li>
          	<ul>
          		<li><a ref="#" >----Historial de Compras</a></li>
          		<li><a ref="#" >----Preguntas Realizadas</a></li>
          		<li><a ref="#" >----Preguntas Contestadas</a></li>
          		<li><a ref="#" >----Compras en seguimiento</a></li>
          	</ul>
          <li id="km_opt2"><a href="<?php $this->baseUrl() ?>/usuario/venta/ventasactivas">Mis Ventas</a></li>
          	<ul>
	          	<li><a ref="#" >----Ventas Activas</a></li>
          		<li><a ref="#" >----Ventas no Activas</a></li>
          		<li><a ref="#" >----Preguntas Recibidas</a></li>
          		<li><a ref="#" >----Preguntas Contestadas</a></li>
          	</ul>
          		
          <li id="km_opt3"><a href="<?php $this->baseUrl() ?>/usuario/calificaciones/calificacionespendientes">Mis Calificaciones</a></li>
          	<ul>
          		<li><a ref="#" >----Calificaciones Pendientes</a></li>
          		<li><a ref="#" >----Calificaciones Realizadas</a></li>
          		<li><a ref="#" >----Ver Reputacion</a></li>
          	</ul>
          <li id="km_opt4"><a href="<?php $this->baseUrl() ?>/usuario/pagos/pendiente-de-pago">Kotear Pagos</a></li>
          	<ul>
				<li><a ref="#" >----Cargos Pagados</a></li>
				<li><a ref="#" >----Pendientes de Pago</a></li>
          	</ul>
          <li id="km_opt5"><a href="<?php $this->baseUrl()?>/usuario/edicion">Mis Datos</a></li>
          	<ul>
          		<li><a ref="#" >----Actualiza tus Datos de Contacto</a></li>
          		
          	</ul>
        </ul>
       <!--   <ul class="koteando_tabs_menu">
          <li class="active"><a href="#">Historial de Compras</a></li>
          <li><a href="#">Compras en Seguimiento</a></li>
          <li><a href="#">Preguntas Realizadas</a></li>
        </ul>
        <ul class="koteando_rightmenu">
          <li><a href="#">Ayuda</a></li>
          <li><a href="#">Preguntas Frecuentes</a></li>
        </ul>-->
</div>
